USE duan2026;

CREATE TABLE IF NOT EXISTS lien_he (
  id INT(11) NOT NULL AUTO_INCREMENT,
  ho_ten VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  so_dien_thoai VARCHAR(20) DEFAULT NULL,
  noi_dung TEXT NOT NULL,
  ngay_gui DATETIME DEFAULT CURRENT_TIMESTAMP,
  trang_thai VARCHAR(50) DEFAULT 'pending',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
